Task23_Low/Controllers/GuestController.cs
using AutoMapper;
using BLL;
using BLL.Interfaces;
using BLL.Services;
using DAL1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class GuestController : Controller
    {
        private IReviewsService reviewsService;
        public GuestController(IReviewsService serv)
        {
            reviewsService = serv;
        }
        // GET: Guest
        public ActionResult Index(int? page)
        {
            IEnumerable<ReviewDTO> reviewsDtos = reviewsService.GetReviews();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ReviewDTO, ReviewViewModel>()).CreateMapper();
            var reviews = mapper.Map<IEnumerable<ReviewDTO>, List<ReviewViewModel>>(reviewsDtos);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(reviews.ToPagedList(pageNumber, pageSize));
        }
    }
}

Task23_Low/Controllers/MainController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using PagedList;
using DAL1.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Task23_Advanced.Models;
using System;
using System.Linq;

namespace Task23_Advanced.Controllers
{
    public class MainController : Controller
    {
        private IArticlesService articlesService;
        /// <summary>
        /// Main Contoller to represent Articles
        /// </summary>
        /// <param name="serv"></param>
        public MainController(IArticlesService serv)
        {
            articlesService = serv;
        }
        // GET: Main
        public ActionResult Index(string sortOrder,int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            IEnumerable<ArticleDTO> articlesDtos = articlesService.GetArticles();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ArticleDTO, ArticleViewModel>()).CreateMapper();
            var articles = mapper.Map<IEnumerable<ArticleDTO>, List<ArticleViewModel>> (articlesDtos);
            var TagsDtos = articlesService.GetAllTags();
            var TagsMapper = new MapperConfiguration(cfg => cfg.CreateMap<TagsDTO, TagsViewModel>()).CreateMapper();
            var tags = TagsMapper.Map<IEnumerable<TagsDTO>, List<TagsViewModel>>(TagsDtos);
            var dividedArticles = new List<DividedArticlesViewModel>();
            ViewBag.Tags = tags;
            foreach(var article in articles)
            {
                var lessContent = article.Content.Substring(0,199);
                var moreContent = article.Content.Substring(199);
                dividedArticles.Add(new DividedArticlesViewModel
                {
                    Date = article.Date,
                    LessContent = lessContent,
                    MoreContent = moreContent,
                    AuthorName = article.Name,
                    Id = article.Id,
                    Tags = article.Tags
                    
                }) ;
            }
            switch (sortOrder)
            {
                case "name_desc":
                    dividedArticles = dividedArticles.OrderByDescending(s => s.AuthorName).ToList();
                    break;
                case "Date":
                    dividedArticles = dividedArticles.OrderBy(s => s.Date).ToList();
                    break;
                case "date_desc":
                    dividedArticles = dividedArticles.OrderByDescending(s => s.Date).ToList();
                    break;
                default:
                    dividedArticles = dividedArticles.OrderBy(s => s.Id).ToList(); 
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(dividedArticles.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ArticlesByTag(string tagName)
        {
            IEnumerable<ArticleDTO> articlesDtos = articlesService.GetArticles();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ArticleDTO, ArticleViewModel>()).CreateMapper();
            var articles = mapper.Map<IEnumerable<ArticleDTO>, List<ArticleViewModel>>(articlesDtos);
            var TagsDtos = articlesService.GetAllTags();
            var TagsMapper = new MapperConfiguration(cfg => cfg.CreateMap<TagsDTO, TagsViewModel>()).CreateMapper();
            var tags = TagsMapper.Map<IEnumerable<TagsDTO>, List<TagsViewModel>>(TagsDtos);
            var dividedArticles = new List<DividedArticlesViewModel>();           
            ViewBag.Tags = tags;
            foreach (var article in articles)
            {
                var lessContent = article.Content.Substring(0, 199);
                var moreContent = article.Content.Substring(199);
                dividedArticles.Add(new DividedArticlesViewModel
                {
                    Date = article.Date,
                    LessContent = lessContent,
                    MoreContent = moreContent,
                    AuthorName = article.Name,
                    Id = article.Id,
                    Tags = article.Tags

                });
            }
            var dividedArticlesByTag = dividedArticles.Where(i=>i.Tags.Any(p=>p.Name==tagName));
            return View(dividedArticlesByTag.ToList());
        }
        [HttpPost]
        public string AddTag(FormCollection form)
        {
            var id = form["Articles"];
            var tagName = form["Tags"];
            var tagNameFromForm = form["TagName"];
            if(tagName == "" && tagNameFromForm.Length < 3)
            {
                return "TagName must be more than 2";
            }
            if (tagName == "")
            {
                var addstatus = articlesService.AddTag(Convert.ToInt32(id), tagNameFromForm);
                if (addstatus == "There is already that tag name on passed article")
                {
                    return "There is already that tag name on passed article";
                }
            }
            else
            {
                var addstatus = articlesService.AddTag(Convert.ToInt32(id), tagName);
                if(addstatus=="There is already that tag name on passed article")
                {
                    return "There is already that tag name on passed article";
                }
            }
            return "Successfully added new tag";        
        }
    }
}

Task23_Low/Controllers/QuestionnaireController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
namespace Task23_Advanced.Controllers
{
    public class QuestionnaireController : Controller
    {
       
        public ActionResult Index()
        {
            ViewBag.Scales = false;
            ViewBag.Horns = false;
            ViewBag.City = false;
            ViewBag.Works = false;
            
            return View();
        }
        public JsonResult IsFullNameCorrect(string FullName)
        {
            Regex pattern =new Regex( @"[a-zA-Z'-'\s]*");
            if (pattern.IsMatch(FullName))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }
       [HttpGet]
        public JsonResult IsEmailAvailable(string Email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(Email);
                if (addr.Address == Email)
                    return Json(true,JsonRequestBehavior.AllowGet);
                else
                    return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch
            {

                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult UserPassedData(FormCollection form)
        {

            ViewBag.TextReturn = "Your input fullname: " + form["Text"];
            ViewBag.AdressReturn = "Your input adress: " + form["Adress"];
            ViewBag.ScalesReturn = "You do not have scales";
            ViewBag.HornsReturn = "You do not have horns";
            ViewBag.RegionReturn = "Your input region: " + form["Region"];
            ViewBag.OrganisationReturn = "Your input organisation: " + form["Organisation"];
            ViewBag.EmailReturn = "Your input email: " + form["Email"];
            if (Convert.ToBoolean(form["Check-box-scales"].Split(',')[0]))
            {
                ViewBag.ScalesReturn = "You have scales";
            }
            if (Convert.ToBoolean(form["Check-box-horns"].Split(',')[0]))
            {
                ViewBag.HornsReturn = "You have horns";
            }
            ViewBag.CityReturn = "You did not checked city";
            if (form["Check-box-city"] != null && Convert.ToBoolean(form["Check-box-city"].Split(',')[0]))
            {
                ViewBag.CityReturn = "You checked city";
            }
            ViewBag.WorkReturn = "You did not checked work";
            if (form["Check-box-work"] != null && Convert.ToBoolean(form["Check-box-work"].Split(',')[0]))
            {
                ViewBag.WorkReturn = "You checked work";
            }
            ViewBag.CountryReturn = "Your input country: " + form["Country"];
            ViewBag.ExperienceReturn = "Your input experience : " + form["Experience"];
            ViewBag.PositionReturn = "Your input position: " + form["Position"];
            return View();
        }
    }
}

Task23_Low/Views/Main/ArticlesByTag.cshtml
@model List<Task23_Advanced.Models.DividedArticlesViewModel>
@using Task23_Advanced.Models;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "";
    ViewBag.Title = "Main page of library";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/Main.css" />
    <script type="text/javascript">
        function myFunction(id) {
            var dots = document.getElementById("dots".concat(id));
            var moreText = document.getElementById(id);
            var btnText = document.getElementById("ReadMore".concat(id));

            if (dots.style.display === "none") {
                dots.style.display = "inline";
                btnText.innerHTML = "Read more";
                moreText.style.display = "none";
            } else {
                dots.style.display = "none";
                btnText.innerHTML = "Read less";
                moreText.style.display = "inline";
            }
        }
    </script>
</head>
<body>
    @{
        List<TagsViewModel> tags = ViewBag.Tags;
    }
    <div class="navbar navbar-dark bg-dark ">
        <ul class="nav ">
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index", "Main")">Main</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index", "Guest")">Guest</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index", "Questionnaire")">Questionnaire</a>
            </li>

        </ul>
    </div>


    <div class="d-flex justify-content-end">
        <button class="btn bg-danger btn-lg" data-bs-target="#login" data-bs-toggle="modal" id="add-tags">Add tags to articles</button>
    </div>
    @using (Html.BeginForm("AddTag", "Main", FormMethod.Post))
    {
        <div class="modal" id="login" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2>Add tags</h2>
                    </div>
                    <div class="modal-body">
                        <div class="d-flex justify-content-center">
                            <p>Select Article Number</p>
                        </div>
                        <div class="d-flex justify-content-center">

                            @Html.DropDownList("Articles", new SelectList(Model.Select(i => i.Id), "Id"), new { @class = "form-control" })
                        </div>
                        <div class="d-flex justify-content-center">
                            <p>Select Existing Tag or Pass a New One</p>
                        </div>
                        <div class="d-flex justify-content-center">

                            <select class="form-control" id="Tags" name="Tags">
                                <option value="">Select Existing Tag</option>
                                @foreach (var tag in tags)
                                {
                                    <option>@(tag.Name)</option>
                                }
                            </select>
                        </div>
                        <div class="d-flex justify-content-center">

                            <input class="form-control" id="TagName" name="TagName" type="text" value="">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default" data-bs-dismiss="modal">Add Tags</button>
                        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel </button>
                    </div>
                </div>
            </div>
        </div>
    }
    @foreach (var item in Model)
    {
        foreach (var tag in item.Tags)
        {
            <a href=@Url.Action("ArticlesByTag", "Main", new { tagName = tag.Name })>#@(tag.Name)</a>}
        <article>
            <h2> @(item.Id).@Html.DisplayFor(modelItem => item.AuthorName)</h2>
            <h3>@Html.DisplayFor(modelItem => item.Date)</h3>
        </article>
        <p>
            @Html.DisplayFor(modelItem => item.LessContent)<span id="dots@(item.Id)">...</span>
            <span class="more-content" id="@(item.Id)">
                @Html.DisplayFor(modelItem => item.MoreContent)
            </span>
        </p>
        <div class="d-flex justify-content-end">
            <button class="btn btn-dark btn-lg" onclick="myFunction(@(item.Id))" id="ReadMore@(item.Id)">Read more</button>
        </div>
    }
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/articlescript.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/script.js")

    @Scripts.Render("~/Scripts/bootstrap.js")
</body>
</html>

Task23_Low/Views/Main/Index.cshtml
@model PagedList.IPagedList<Task23_Advanced.Models.DividedArticlesViewModel>
@using PagedList.Mvc;
@using Task23_Advanced.Models;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "";
    ViewBag.Title = "Main page of library";
}

<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        <link rel="stylesheet" href="~/Content/Main.css" />
        <script type="text/javascript">
            function myFunction(id) {
                var dots = document.getElementById("dots".concat(id));
                var moreText = document.getElementById(id);
                var btnText = document.getElementById("ReadMore".concat(id));

                if (dots.style.display === "none") {
                    dots.style.display = "inline";
                    btnText.innerHTML = "Read more";
                    moreText.style.display = "none";
                } else {
                    dots.style.display = "none";
                    btnText.innerHTML = "Read less";
                    moreText.style.display = "inline";
                }
            }
        </script>
    </head>
    <body>
        @{
            List<TagsViewModel> tags = ViewBag.Tags;
        }
        <div class="navbar navbar-dark bg-dark ">
            <ul class="nav ">
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Main")">Main</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Guest")">Guest</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Questionnaire")">Questionnaire</a>
                </li>

            </ul>
        </div>


        <div class="d-flex justify-content-end">
            <button class="btn bg-danger btn-lg" data-bs-target="#login" data-bs-toggle="modal" id="add-tags">Add tags to articles</button>
        </div>
        @using (Html.BeginForm("AddTag", "Main", FormMethod.Post))
        {
            <div class="modal" id="login" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h2>Add tags</h2>
                        </div>
                        <div class="modal-body">
                            <div class="d-flex justify-content-center">
                                <p>Select Article Number</p>
                            </div>
                            <div class="d-flex justify-content-center">

                                @Html.DropDownList("Articles", new SelectList(Model.Select(i => i.Id), "Id"), new { @class = "form-control" })
                            </div>
                            <div class="d-flex justify-content-center">
                                <p>Select Existing Tag or Pass a New One</p>
                            </div>
                            <div class="d-flex justify-content-center">

                                <select class="form-control" id="Tags" name="Tags">
                                    <option value="">Select Existing Tag</option>
                                    @foreach (var tag in tags)
                                    {
                                        <option>@(tag.Name)</option>
                                    }
                                </select>
                            </div>
                            <div class="d-flex justify-content-center">

                                <input class="form-control" id="TagName" name="TagName" type="text" value="">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-default" data-bs-dismiss="modal">Add Tags</button>
                            <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel </button>
                        </div>
                    </div>
                </div>
            </div>
        }
    <div class="container d-flex justify-content-evenly" id="sortButtons">
        @Html.ActionLink("Sort by Author Name", "Index", new { sortOrder = ViewBag.NameSortParm },new { @class="sort-link"})

        @Html.ActionLink("Sort by Article Date", "Index", new { sortOrder = ViewBag.DateSortParm }, new { @class = "sort-link" })
    </div>

        @foreach (var item in Model)
        {
            foreach (var tag in item.Tags)
            {
                <a href=@Url.Action("ArticlesByTag", "Main", new { tagName = tag.Name })>#@(tag.Name)</a>
    }
            <article>
                <h2> @(item.Id).@Html.DisplayFor(modelItem => item.AuthorName)</h2>
                <h3>@Html.DisplayFor(modelItem => item.Date)</h3>
            </article>
            <p>
                @Html.DisplayFor(modelItem => item.LessContent)<span id="dots@(item.Id)">...</span>
                <span class="more-content" id="@(item.Id)">
                    @Html.DisplayFor(modelItem => item.MoreContent)
                </span>
            </p>
            <div class="d-flex justify-content-end">
                <button class="btn btn-dark btn-lg" onclick="myFunction(@(item.Id))" id="ReadMore@(item.Id)">Read more</button>
            </div>
        }
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page , sortOrder = ViewBag.CurrentSort }))
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/articlescript.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/Scripts/script.js")

        @Scripts.Render("~/Scripts/bootstrap.js")
    </body>
</html>